/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e596a268-d682-41cb-88c1-d7ea4689c79a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3oDvf90bk",
    "aws_user_pools_web_client_id": "2igd21nf6nll9adsbm0nrh4l90",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://wuc23fkyavheffnm67o7xgc72a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-6djr7x4n7vh6tetkyocjgjyebi",
    "aws_user_files_s3_bucket": "togobyus5d731679bd394593a6f25da8996a3726133853-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
