/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c4a354e8-7d1e-45fb-bb7d-43159839e1a5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3oDvf90bk",
    "aws_user_pools_web_client_id": "2igd21nf6nll9adsbm0nrh4l90",
    "oauth": {
        "domain": "1gyz90k4c10v-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://192.168.100.84:19000/--/",
        "redirectSignOut": "exp://192.168.100.84:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://wuc23fkyavheffnm67o7xgc72a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-6djr7x4n7vh6tetkyocjgjyebi",
    "aws_user_files_s3_bucket": "togobyus5d731679bd394593a6f25da8996a3726133853-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
